== Spel

=== 上下文

[plantuml,spring-framework-expression-context.png]
--
@startuml
interface EvaluationContext {
    Object lookupVariable(String name)
    
    List<PropertyAccessor> getPropertyAccessors();
}
class StandardEvaluationContext {

}

EvaluationContext <|.. StandardEvaluationContext
@enduml
--

=== 解析表达式

===== 核心类图

[plantuml,spring-framework-expression-parser.png]
--
@startuml
interface ExpressionParser {
    Expression parseExpression(String expressionString, ParserContext context)
}
class TemplateAwareExpressionParser {
    SpelExpression doParseExpression(String expressionString, ParserContext context)
}
class InternalSpelExpressionParser {

}
class SpelExpressionParser {

}

interface Expression {
    Object getValue();
}
class SpelExpression {
    private SpelNodeImpl ast;
}
class SpelNodeImpl {
    protected SpelNodeImpl[] children;

    Object getValue(ExpressionState expressionState)
    abstract TypedValue getValueInternal(ExpressionState expressionState)
}

ExpressionParser <|.. TemplateAwareExpressionParser
TemplateAwareExpressionParser <|-- InternalSpelExpressionParser
TemplateAwareExpressionParser <|-- SpelExpressionParser
Expression <|.. SpelExpression

SpelExpressionParser .. InternalSpelExpressionParser
SpelExpressionParser .. SpelExpression
SpelExpression --> SpelNodeImpl
@enduml
--

* SpelExpressionParser使用TemplateAwareExpressionParser.doParseExpression解析表达式，生成SpelExpression对象
* SpelExpression持有SpelNodeImpl用于表达式取值

=== 取值

[plantuml,spring-framework-expression-value.png]
--
@startuml
class SpelNodeImpl {
    protected SpelNodeImpl[] children;

    Object getValue(ExpressionState expressionState)
    abstract TypedValue getValueInternal(ExpressionState expressionState)
}

class CompoundExpression {
}
class VariableReference {
}
class PropertyOrFieldReference {
}

SpelNodeImpl <|-- CompoundExpression
SpelNodeImpl <|-- VariableReference
SpelNodeImpl <|-- PropertyOrFieldReference
@enduml
--

* SpelNodeImpl有很多实现，其中PropertyOrFieldReference最关键
* PropertyOrFieldReference可以组合PropertyAccessor使用


=== 自定义解析器

[plantuml,spring-framework-expression-propertyaccessor.png]
--
@startuml
interface PropertyAccessor {
    Class<?>[] getSpecificTargetClasses();
    
    TypedValue read(EvaluationContext context, Object target, String name);
}
class ReflectivePropertyAccessor {
}
class JsonPropertyAccessor {
}

PropertyAccessor <|-- ReflectivePropertyAccessor
PropertyAccessor <|-- JsonPropertyAccessor
@enduml
--

* PropertyAccessor#getSpecificTargetClasses可以指定处理哪些Class
* ReflectivePropertyAccessor 为默认实现，通过反射取值
* JsonPropertyAccessor通过ObjectMapper取值，包路径：org.springframework.integration.json

